---
jql_project_mapping:
  'assignee = harst AND filter not in ("Finished Tickets")': 'Magazino JIRA'
  'creator = harst AND assignee = harst AND NOT filter = "Finished Tickets" ORDER BY createdDate': 'JIRA: Needs my input'
  'project in ("PM: Fiege - Pilot", "Software development") AND assignee = harst AND NOT filter in ("Finished Tickets")': 'JIRA: Fiege'

config_path:
  '~/.password_store'

jira_server_url:
  'http://magazino.atlassian.net'

